name: Continuous_Integration
on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest]
        python: ["3.8", "3.9"]
    steps:
      #- uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
       #print the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      # print OS version
      - name: Display os version
       run: python -c "import platform; print(platform.system())"
      - name: Pip install package
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Poetry install package
        run: |
          pip install poetry
          poetry install
      - name: Linting
        run: |
          poetry run pydocstyle --convention=google
          poetry run isort . --check
          poetry run black . --check
          poetry run flake8 . --ignore E501,F401,W503 --count
        continue-on-error: True
