name: Testing and Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Testing and Coverage
    steps:
    - uses: actions/checkout@v1
      with:
          python-version: '3.9'
    - name: Installation
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Run tests and collect coverage
      run: | 
        pip install codecov
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
        codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        files: /home/runner/work/symmer/symmer/coverage.xml
        flags: tests
